version: '3.9'

services:
  apache:
    build: ./core
    restart: always
    volumes:
      - ./core:/usr/local/apache2/htdocs/
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "5000:5001"
    volumes:
      - ./db:/docker-entrypoint-initdb.d   